stages:
  - update_all

variables:
  SSH_CONNECTION: 
    value: $SSH_CONNECTION_PROD
    description: "SSH connection string"
    rules:
      - if: $CI_COMMIT_BRANCH == "master"
        value: $SSH_CONNECTION_PROD
      - if: $CI_COMMIT_BRANCH == "dev"
        value: $SSH_CONNECTION_DEV

update_all:
  stage: update_all
  variables:
    SECURE_FILES_DOWNLOAD_PATH: '.ssh/'
  script:
    # download-secure-files
    - curl -s https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer | bash
    - chmod 600 .ssh/id_ed25519
    - chmod 644 .ssh/id_ed25519.pub
    - echo $SSH_CONNECTION
    # pull latest from github
    - ssh $SSH_CONNECTION "cd /var/www/linepig; sudo git pull; cd laravel; sudo php artisan config:clear; sudo php artisan config:cache; sudo chown -R apache:apache /var/www/linepig;"
