stages:
  - update-all
  - composer-update

variables:
  SITEPATH: "/var/www/linepig"

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      variables:
        SSH_CONNECTION: "-i .ssh/id_ed25519 -tt -J fmit@107.0.125.6:54879 fmit@10.255.1.18"
      when: always
    - if: $CI_COMMIT_BRANCH == "dev"
      variables:
        SSH_CONNECTION: "-i .ssh/id_ed25519 -tt fmit@10.100.111.141"
      when: always

git-update:
  stage: update-all
  variables:
    SECURE_FILES_DOWNLOAD_PATH: '.ssh/'
  script:
    # download-secure-files
    - curl -s https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer | bash
    - chmod 600 .ssh/id_ed25519
    - chmod 644 .ssh/id_ed25519.pub
    - echo $SSH_CONNECTION
    # pull latest from github
    - ssh $SSH_CONNECTION "cd $SITEPATH; sudo git pull; cd laravel; sudo php artisan optimize:clear; sudo chown -R apache:apache $SITEPATH;"

composer:
  stage: composer-update
  variables:
    SECURE_FILES_DOWNLOAD_PATH: '.ssh/'
  script:
    - curl -s https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer | bash
    - chmod 600 .ssh/id_ed25519
    - chmod 644 .ssh/id_ed25519.pub
    - echo $SSH_CONNECTION
    - ssh $SSH_CONNECTION "cd $SITEPATH; cd laravel; sudo composer update -W; sudo php artisan optimize:clear; sudo chown -R apache:apache $SITEPATH;"
  rules:
    - changes:
        - composer.json
        - composer.lock
