<?php

/**
 * This configuration file is for the BOLD Lookup list.
 */

return [
    'lookup' => [
        'Abacoproeces saltuum',
        'Abiskoa abiskoensis',
        'Acanoides beijingensis',
        'Acanoides hengshanensis',
        'Acanthoneta aggressa',
        'Acanthoneta furcata',
        'Acartauchenius scurrilis',
        'Agnyphantes arboreus',
        'Agnyphantes expunctus',
        'Agyneta affinis',
        'Agyneta allosubtilis',
        'Agyneta alpica',
        'Agyneta amersaxatilis',
        'Agyneta amersaxatilis cf.',
        'Agyneta angulata',
        'Agyneta brevis',
        'Agyneta bucklei',
        'Agyneta cauta',
        'Agyneta cincta',
        'Agyneta conigera',
        'Agyneta danielbelangeri',
        'Agyneta darrelli',
        'Agyneta darrelli cf.',
        'Agyneta decora',
        'Agyneta decorata',
        'Agyneta dynica',
        'Agyneta evadens',
        'Agyneta fabra',
        'Agyneta fillmorana',
        'Agyneta fillmorana cf.',
        'Agyneta flibuscrocus',
        'Agyneta floridana',
        'Agyneta fuscipalpa',
        'Agyneta gulosa',
        'Agyneta innotabilis',
        'Agyneta jacksoni',
        'Agyneta lophophor',
        'Agyneta manni',
        'Agyneta maritima',
        'Agyneta micaria',
        'Agyneta mollis',
        'Agyneta mossica',
        'Agyneta nigripes',
        'Agyneta n. sp. 7',
        'Agyneta olivacea',
        'Agyneta ordinaria',
        'Agyneta orites',
        'Agyneta parva',
        'Agyneta perspicua',
        'Agyneta protrudens',
        'Agyneta ramosa',
        'Agyneta ressli',
        'Agyneta ripariensis',
        'Agyneta rurestris',
        'Agyneta saaristoi',
        'Agyneta saxatilis',
        'Agyneta semipallida',
        'Agyneta serrata',
        'Agyneta sheffordiana',
        'Agyneta silvae',
        'Agyneta similis',
        'Agyneta simplex',
        'Agyneta simplicitarsis',
        'Agyneta sp.',
        'Agyneta sp. 1 FML',
        'Agyneta sp. 1GAB',
        'Agyneta sp. 1-JS',
        'Agyneta sp. 2 FML',
        'Agyneta sp. 2GAB',
        'Agyneta sp. 2-JS',
        'Agyneta sp. 3RB',
        'Agyneta sp. 4GAB',
        'Agyneta sp. 6RB',
        'Agyneta sp. 7RB',
        'Agyneta spD',
        'Agyneta straminicola',
        'Agyneta subtilis',
        'Agyneta trifurcata',
        'Agyneta tuberculata',
        'Agyneta unimaculata',
        'Agyneta uta',
        'Agyneta watertoni',
        'Allomengea dentisetis',
        'Allomengea scopigera',
        'Allomengea sp.',
        'Allomengea vidua',
        'Anguliphantes angulipalpis',
        'Anguliphantes dybowskii',
        'Anguliphantes karpinskii',
        'Anguliphantes monticola',
        'Anguliphantes nasus',
        'Anguliphantes sp.',
        'Anguliphantes zygius',
        'Antrohyphantes sophianus',
        'Aphileta microtarsa',
        'Aphileta misera',
        'Araeoncus anguineus',
        'Araeoncus crassiceps',
        'Araeoncus humilis',
        'Arcterigone pilifrons',
        'Arcuphantes arcuatulus',
        'Arcuphantes pennatus',
        'Arcuphantes sylvaticus',
        'Asemostera daedalus',
        'Asemostera janetae',
        'Asiceratinops kolymensis',
        'Asperthorax borealis',
        'Asthenargus edentulus',
        'Asthenargus helveticus',
        'Asthenargus paganus',
        'Australolinyphia remota',
        'Baryphyma pratense',
        'Baryphyma trifrons',
        'Baryphyma trifrons affine',
        'Bathylinyphia maior',
        'Bathyphantes alascensis',
        'Bathyphantes alboventris',
        'Bathyphantes approximatus',
        'Bathyphantes brevipes',
        'Bathyphantes brevis',
        'Bathyphantes canadensis',
        'Bathyphantes diasosnemis',
        'Bathyphantes eumenis',
        'Bathyphantes gracilis',
        'Bathyphantes iviei',
        'Bathyphantes keeni',
        'Bathyphantes latescens',
        'Bathyphantes malkini',
        'Bathyphantes nigrinus',
        'Bathyphantes orica',
        'Bathyphantes pallidus',
        'Bathyphantes parvulus',
        'Bathyphantes pogonias',
        'Bathyphantes reprobus',
        'Bathyphantes setiger',
        'Bathyphantes similis',
        'Bathyphantes simillimus',
        'Bathyphantes tongluensis',
        'Bathyphantes waneta',
        'Batueta cuspidata',
        'Batueta similis',
        'Bifurcia curvata',
        'Bifurcia ramosa',
        'Bolephthyphantes index',
        'Bolyphantes alticeps',
        'Bolyphantes bipartitus',
        'Bolyphantes luteolus',
        'Bolyphantes sacer',
        'Bolyphantes sp.',
        'Capsulia sp. 1 QW-2007',
        'Caracladus avicula',
        'Caracladus zamoniensis',
        'Carorita limnaea',
        'Carorita sp. 1GAB',
        'Centromerita bicolor',
        'Centromerus acutidentatus',
        'Centromerus albidus',
        'Centromerus arcanus',
        'Centromerus brevipalpus',
        'Centromerus brevivulvatus',
        'Centromerus cavernarum',
        'Centromerus cornupalpis',
        'Centromerus denticulatus',
        'Centromerus dilutus',
        'Centromerus furcatus',
        'Centromerus incilium',
        'Centromerus lakatnikensis',
        'Centromerus levitarsis',
        'Centromerus longibulbus',
        'Centromerus minor',
        'Centromerus nr. longibulbus',
        'Centromerus pabulator',
        'Centromerus pacificus',
        'Centromerus persolutus',
        'Centromerus semiater',
        'Centromerus serratus',
        'Centromerus silvicola',
        'Centromerus sp. 2GAB',
        'Centromerus sp. 3GAB',
        'Centromerus subalpinus',
        'Centromerus sylvaticus',
        'Centromerus trilobus',
        'Ceraticelus artemisiae',
        'Ceraticelus atriceps',
        'Ceraticelus bulbosus',
        'Ceraticelus crassiceps',
        'Ceraticelus fissiceps',
        'Ceraticelus laetabilis',
        'Ceraticelus laetus',
        'Ceraticelus laticeps',
        'Ceraticelus limnologicus',
        'Ceraticelus minutus',
        'Ceraticelus rowensis',
        'Ceraticelus silus',
        'Ceraticelus similis',
        'Ceraticelus vesperus',
        'Ceratinella acerea',
        'Ceratinella alaskae',
        'Ceratinella brevipes',
        'Ceratinella brevis',
        'Ceratinella brunnea',
        'Ceratinella ornatula',
        'Ceratinella ornatula alaskana',
        'Ceratinella parvula',
        'Ceratinella scabrosa',
        'Ceratinella sp.',
        'Ceratinella tigana',
        'Ceratinella wideri',
        'Ceratinops annulipes',
        'Ceratinops crenatus',
        'Ceratinopsidis formosa',
        'Ceratinops inflatus',
        'Ceratinopsis auriculata',
        'Ceratinopsis labradorensis',
        'Ceratinopsis laticeps',
        'Ceratinopsis nigriceps',
        'Ceratinopsis nigripalpis',
        'Ceratinopsis setoensis',
        'Ceratinopsis swanea',
        'Ceratinops latus',
        'Ceratinops littoralis',
        'Ceratinops obscurus',
        'Ceratinops rugosus',
        'Ceratinops sylvaticus',
        'Cheniseo sphagnicultor',
        'Cinetata gradata',
        'Cnephalocotes obscurus',
        'Collinsia holmgreni',
        'Collinsia inerrans',
        'Collinsia ksenia',
        'Collinsia pertinens',
        'Collinsia plumosa',
        'Collinsia spetsbergensis',
        'Collinsia stylifera',
        'Collinsia thulensis',
        'Coloncus siou',
        'Concavocephalus rubens',
        'Connithorax barbatus',
        'Coreorgonal monoceros',
        'Coreorgonal petulcus',
        'Crispiphantes sp.',
        'Denisiphantes sp.',
        'Diastanillus pecuarius',
        'Dicymbium elongatum',
        'Dicymbium facetum',
        'Dicymbium libidinosum',
        'Dicymbium nigrum',
        'Dicymbium nigrum brevisetosum',
        'Dicymbium sinofacetum',
        'Dicymbium tibiale',
        'Dicymbium yaginumai',
        'Diplocentria bidentata',
        'Diplocentria perplexa',
        'Diplocentria rectangulata',
        'Diplocentria retinax',
        'Diplocephalus barbiger',
        'Diplocephalus crassilobus',
        'Diplocephalus cristatus',
        'Diplocephalus helleri',
        'Diplocephalus latifrons',
        'Diplocephalus mirabilis',
        'Diplocephalus picinus',
        'Diplocephalus sphagnicola',
        'Diplocephalus subrostratus',
        'Diplocephalus uliginosus',
        'Diplostyla concolor',
        'Disembolus corneliae',
        'Disembolus hyalinus',
        'Disembolus implicatus',
        'Disembolus sp. 1GAB',
        'Dismodicus alticeps',
        'Dismodicus bifrons',
        'Dismodicus decemoculatus',
        'Dismodicus elevatus',
        'Dismodicus sp. 1 GAB',
        'Doenitzius pruvus',
        'Donacochara speciosa',
        'Drapetisca alteranda',
        'Drapetisca socialis',
        'Drepanotylus borealis',
        'Drepanotylus uncatus',
        'Dubiaranea cf. caledonica',
        'Dubiaranea difficilis',
        'Dubiaranea distincta',
        'Dubiaranea longiscapa',
        'Dubiaranea sp.',
        'Dubiaranea sp. 10 FML',
        'Dubiaranea sp. 11 FML',
        'Dubiaranea sp. 13 FML',
        'Dubiaranea sp. 1 FML',
        'Dubiaranea sp. 2 FML',
        'Dubiaranea sp. 3 FML',
        'Dubiaranea sp. 4 FML',
        'Dubiaranea sp. 6 FML',
        'Eldonnia sp.',
        'Entelecara acuminata',
        'Entelecara congenera',
        'Entelecara media',
        'Entelecara sombra',
        'Eridantes erigonoides',
        'Eridantes utibilis',
        'Erigone aletris',
        'Erigone alsaida',
        'Erigone antegona',
        'Erigone arctica',
        'Erigone arctica palearctica',
        'Erigone arctica sibirica',
        'Erigone arcticola',
        'Erigone arctophylacis',
        'Erigone atra',
        'Erigone autumnalis',
        'Erigone blaesa',
        'Erigone cristatopalpus',
        'Erigone dentigera',
        'Erigone dentipalpis',
        'Erigone dentosa',
        'Erigone hypoarctica',
        'Erigone koshiensis',
        'Erigonella hiemalis',
        'Erigonella ignobilis',
        'Erigonella subelevata',
        'Erigone longipalpis',
        'Erigone prominens',
        'Erigone psychrophila',
        'Erigone remota',
        'Erigone sp.',
        'Erigone sp. 10 FML',
        'Erigone svenssoni',
        'Erigone tirolensis',
        'Erigone welchi',
        'Erigonoplus globipes',
        'Erigonoplus jarmilae',
        'Eskovia exarmata',
        'Eskovina clava',
        'Estrandia grandaeva',
        'Eulaira arctoa',
        'Eulaira chelata',
        'Eulaira dela',
        'Eulaira obscura',
        'Eulaira sp. 1GAB',
        'Evansia merens',
        'Fissiscapus sp. 1 FML',
        'Flagelliphantes flagellifer',
        'Floricomus plumalis',
        'Floricomus rostratus',
        'Floricomus sp. 1GAB',
        'Florinda coccinea',
        'Floronia bucculenta',
        'Frederickus coylei',
        'Frederickus wilburi',
        'Frontinella communis',
        'Frontinella frutetorum',
        'Frontinella huachuca',
        'Frontinella potosia',
        'Frontinella zhui',
        'Frontinellina frutetorum',
        'Gibothorax tchernovi',
        'Gigapassus octarine',
        'Gladiata fengli',
        'Glyphesis cottonae',
        'Glyphesis idahoanus',
        'Glyphesis scopulifer',
        'Glyphesis servulus',
        'Gnathonarium dentatum',
        'Gnathonarium famelicum',
        'Gnathonarium suppositum',
        'Gnathonarium taczanowskii',
        'Gnathonaroides pedalis',
        'Gonatium crassipalpum',
        'Gonatium hilare',
        'Gonatium paradoxum',
        'Gonatium rubellum',
        'Gonatium rubens',
        'Gongylidiellum latebricola',
        'Gongylidiellum murcidum',
        'Gongylidiellum vivum',
        'Gongylidioides rimatus',
        'Gongylidium rufipes',
        'Grammonota angusta',
        'Grammonota capitata',
        'Grammonota gentilis',
        'Grammonota gigas',
        'Grammonota inornata',
        'Grammonota kincaidi',
        'Grammonota maritima',
        'Grammonota ornata',
        'Grammonota pictilis',
        'Grammonota secata',
        'Grammonota sp. 1 FML',
        'Grammonota sp. 1GAB',
        'Grammonota sp. 2 FML',
        'Grammonota sp. 2GAB',
        'Grammonota subarctica',
        'Grammonota teresta',
        'Grammonota texana',
        'Grammonota vittata',
        'Gravipalpus standifer',
        'Halorates n. sp.',
        'Halorates reprobus',
        'Halorates stylifer',
        'Haplinis diloris',
        'Helophora insignis',
        'Helophora reducta',
        'Helophora tunagyna',
        'Hilaira canaliculata',
        'Hilaira devitata',
        'Hilaira excisa',
        'Hilaira herniosa',
        'Hilaira minuta',
        'Hilaira nubigena',
        'Hilaira pervicax',
        'Hilaira proletaria',
        'Hilaira sibirica',
        'Hilaira vexatrix',
        'Hilaria glacialis',
        'Holminaria prolata',
        'Horcotes quadricristatus',
        'Horcotes strandi',
        'Houshenzinus xiaolongha',
        'Hybauchenidium aquilonare',
        'Hybauchenidium cymbadentatum',
        'Hybauchenidium gibbosum',
        'Hybauchenidium sp2-GAB',
        'Hylyphantes graminicola',
        'Hypomma bituberculatum',
        'Hypomma cornutum',
        'Hypomma fulvum',
        'Hypomma marxi',
        'Hypomma subarcticum',
        'Hypselistes florens',
        'Hypselistes jacksoni',
        'Hypselistes semiflavus',
        'Idionella rugosa',
        'Improphantes complicatus',
        'Improphantes geniculatus',
        'Improphantes nitidus',
        'Improphantes sp. 1GAB',
        'Improphantes sp. 1RB',
        'Incestophantes crucifer',
        'Incestophantes duplicatus',
        'Incestophantes frigidus',
        'Incestophantes kochiellus',
        'Incestophantes lamprus',
        'Incestophantes laricetorum',
        'Incestophantes mercedes',
        'Incestophantes sp. 1 GAB',
        'Incestophantes washingtoni',
        'Ipa keyserlingi',
        'Islandiana cristata',
        'Islandiana falsifica',
        'Islandiana flaveola',
        'Islandiana holmi',
        'Islandiana lasalana',
        'Islandiana longisetosa',
        'Islandiana princeps',
        'Ivielum sibiricum',
        'Janetschekia monodon',
        'Kaestneria dorsalis',
        'Kaestneria pullata',
        'Kaestneria rufula',
        'Kikimora palustris',
        'Labulla thoracica',
        'Laminacauda ansoni',
        'Laminacauda tucumani',
        'Lasiargus hirsutus',
        'Lasiargus sp.',
        'Lepthyphantes alpinus',
        'Lepthyphantes furcillifer',
        'Lepthyphantes hamifer',
        'Lepthyphantes intricatus',
        'Lepthyphantes keyserlingi',
        'Lepthyphantes leprosus',
        'Lepthyphantes luteipes',
        'Lepthyphantes minutus',
        'Lepthyphantes nodifer',
        'Lepthyphantes rainieri',
        'Lepthyphantes sp. 12',
        'Lepthyphantes sp. 12RB',
        'Lepthyphantes sp. 2RB',
        'Lepthyphantes turbatrix',
        'Leptorhoptrum robustum',
        'Leptothrix hardyi',
        'Lessertia dentichelis',
        'Linyphantes aeronauticus',
        'Linyphantes anacortes',
        'Linyphantes nehalem',
        'Linyphantes nigrescens',
        'Linyphantes orcinus',
        'Linyphantes pacificus',
        'Linyphantes pualla',
        'Linyphantes sp.',
        'Linyphantes sp. 1GAB',
        'Linyphantes victoria',
        'Linyphia hortensis',
        'Linyphia mimonti',
        'Linyphia tenuipalpis',
        'Linyphia triangularis',
        'Linyphiidae_IM SP_IM4',
        'Linyphiidae_IM SP_IM5',
        'Linyphiidae_IM SP_IM6',
        'Linyphiidae_IM SP_IM8',
        'Lophomma depressum',
        'Lophomma punctatum',
        'Lophomma vaccinii',
        'Macrargus boreus',
        'Macrargus carpenteri',
        'Macrargus multesimus',
        'Macrargus rufus',
        'Mansuphantes fragilis',
        'Mansuphantes korgei',
        'Mansuphantes mansuetus',
        'Maro amplus',
        'Maro borealis',
        'Maro lehtineni',
        'Maro minutus',
        'Maro nearcticus',
        'Maro n. sp.',
        'Maro sublestus',
        'Masikia indistincta',
        'Maso sp. 1GAB',
        'Maso sundevalli',
        'Mecopisthes peusi',
        'Mecynargus borealis',
        'Mecynargus foveatus',
        'Mecynargus hypnicola',
        'Mecynargus monticola',
        'Mecynargus morulus',
        'Mecynargus paetulus',
        'Mecynargus pinipumilis',
        'Mecynargus sp. 1GAB',
        'Mecynargus sphagnicola',
        'Mecynargus tungusicus',
        'Mecynidis cf. dentipalpis',
        'Mecynidis dentipalpis',
        'Megalepthyphantes collinus',
        'Megalepthyphantes nebulosus',
        'Megalepthyphantes pseudocollinus',
        'Meioneta innotabilis',
        'Meioneta nigripes',
        'Meioneta rurestris',
        'Mermessus augustalis',
        'Mermessus brevidentatus',
        'Mermessus contortus',
        'Mermessus entomologicus',
        'Mermessus fradeorum',
        'Mermessus index',
        'Mermessus jona',
        'Mermessus lindrothi',
        'Mermessus maculatus',
        'Mermessus rapidulus',
        'Mermessus sp. 10 FML',
        'Mermessus sp. 11 FML',
        'Mermessus sp. 1 FML',
        'Mermessus sp. 1GAB',
        'Mermessus sp. 2GAB',
        'Mermessus taibo',
        'Mermessus tridentatus',
        'Mermessus trilobata',
        'Mermessus trilobatus',
        'Mermessus undulatus',
        'Mesasigone mira',
        'Metopobactrus pacificus',
        'Metopobactrus prominulus',
        'Micrargus alpinus',
        'Micrargus apertus',
        'Micrargus georgescuae',
        'Micrargus herbigradus',
        'Micrargus herbigradus cf.',
        'Micrargus sp.',
        'Micrargus subaequalis',
        'Microctenonyx subitaneus',
        'Microlinyphia dana',
        'Microlinyphia impigra',
        'Microlinyphia mandibulata',
        'Microlinyphia pusilla',
        'Microlinyphia sp.',
        'Microlinyphia sp1-GAB',
        'Microlinyphia sterilis',
        'Microneta aterrima',
        'Microneta viaria',
        'Minicia marginella',
        'Minyriolus pusillus',
        'Mioxena blanda',
        'Moebelia penicillata',
        'Monocephalus castaneipes',
        'Monocephalus fuscipes',
        'Moyosi rugosa',
        'Mughiphantes cornutus',
        'Mughiphantes mughi',
        'Mughiphantes nigromaculatus',
        'Mughiphantes pulcher',
        'Mughiphantes sobrius',
        'Mughiphantes sp.',
        'Mughiphantes sp. 1GAB',
        'Mughiphantes taczanowskii',
        'Mughiphantes variabilis',
        'Mythoplastoides erectus',
        'Nasoonaria circinata',
        'Nematogmus sanguinolentus',
        'Neomaso gibber',
        'Neomaso minimus',
        'Neomaso pollicatus',
        'Neonesiotes remiformis',
        'Neriene cavaleriei',
        'Neriene clathrata',
        'Neriene digna',
        'Neriene emphana',
        'Neriene furtiva',
        'Neriene japonica',
        'Neriene limbatinella',
        'Neriene litigiosa',
        'Neriene longipedella',
        'Neriene macella',
        'Neriene montana',
        'Neriene nigripectoris',
        'Neriene oidedicata',
        'Neriene peltata',
        'Neriene radiata',
        'Neriene sp.',
        'Neriene sp. 1GAB',
        'Neriene sp. CJ-013',
        'Neriene sp. TAB-2009',
        'Neriene variabilis',
        'Nippononeta coreana',
        'Notholepthyphantes australis',
        'Notioscopus sarcinatus',
        'Notioscopus sibiricus',
        'Novafroneta vulgaris',
        'Nusoncus nasutus',
        'Obscuriphantes obscurus',
        'Oedothorax agrestis',
        'Oedothorax alascensis',
        'Oedothorax apicatus',
        'Oedothorax fuscus',
        'Oedothorax gibbifer',
        'Oedothorax gibbosus',
        'Oedothorax montifer',
        'Oedothorax retusus',
        'Oedothorax trilobatus',
        'Oia imadatei',
        'Oreoneta banffkluane',
        'Oreoneta brunnea',
        'Oreoneta frigida',
        'Oreoneta garrina',
        'Oreoneta leviceps',
        'Oreoneta tatrica',
        'Oreoneta tienshangensis',
        'Oreonetides filicatus',
        'Oreonetides flavescens',
        'Oreonetides flavus',
        'Oreonetides glacialis',
        'Oreonetides rectangulatus',
        'Oreonetides rotundus',
        'Oreonetides sp. 1GAB',
        'Oreonetides sp. 2GAB',
        'Oreonetides vaginatus',
        'Oreophantes recurvatus',
        'Orsonwelles ambersonorum',
        'Orsonwelles arcanus',
        'Orsonwelles bellum',
        'Orsonwelles calx',
        'Orsonwelles falstaffius',
        'Orsonwelles graphicus',
        'Orsonwelles iudicium',
        'Orsonwelles macbeth',
        'Orsonwelles malus',
        'Orsonwelles othello',
        'Orsonwelles polites',
        'Orsonwelles ventus',
        'Oryphantes angulatus',
        'Oryphantes bipilis',
        'Oryphantes sp.',
        'Ostearius melanopygius',
        'Pacifiphantes magnificus',
        'Pacifiphantes zakharovi',
        'Palliduphantes antroniensis',
        'Palliduphantes byzantinus',
        'Palliduphantes ericaeus',
        'Palliduphantes insignis',
        'Palliduphantes khobarum',
        'Palliduphantes montanus',
        'Palliduphantes pallidus',
        'Panamomops mengei',
        'Panamomops tauricornis',
        'Paraletes pogo',
        'Parameioneta tricolorata',
        'Paratmeticus bipunctis',
        'Parawubanoides unicornis',
        'Pelecopsis dorniana',
        'Pelecopsis elongata',
        'Pelecopsis janus',
        'Pelecopsis mengei',
        'Pelecopsis moesta',
        'Pelecopsis parallela',
        'Pelecopsis radicicola',
        'Pelecopsis sculpta',
        'Perregrinus deformis',
        'Perro polaris',
        'Perro putoranica',
        'Perro sp. 1GAB',
        'Phlattothrata flagellata',
        'Phlattothrata parva',
        'Phlattothrata sp. 1GAB',
        'Piniphantes pinicola',
        'Pityohyphantes alticeps',
        'Pityohyphantes costatus',
        'Pityohyphantes cristatus',
        'Pityohyphantes limitaneus',
        'Pityohyphantes minidoka',
        'Pityohyphantes phrygianus',
        'Pityohyphantes rubrofasciatus',
        'Pityohyphantes subarcticus',
        'Pityohyphantes tacoma',
        'Pocadicnemis americana',
        'Pocadicnemis juncea',
        'Pocadicnemis occidentalis',
        'Pocadicnemis pumila',
        'Pocobletus sp. 10 FML',
        'Pocobletus sp. 1 FML',
        'Pocobletus sp. MAA-2009',
        'Poeciloneta bihamata',
        'Poeciloneta calcaratus',
        'Poeciloneta canionis',
        'Poeciloneta cf. fructuosa',
        'Poeciloneta fructuosa',
        'Poeciloneta lyrica',
        'Poeciloneta petrophila',
        'Poeciloneta tanasevitchi',
        'Poeciloneta theridiformis',
        'Poeciloneta variegata',
        'Porrhomma boreale',
        'Porrhomma convexum',
        'Porrhomma longjiangense',
        'Porrhomma microphthalmum',
        'Porrhomma montanum',
        'Porrhomma oblitum',
        'Porrhomma pallidum',
        'Porrhomma pygmaeum',
        'Porrhomma rosenhaueri',
        'Porrhomma terrestre',
        'Praestigia groenlandica',
        'Praestigia kulczynskii',
        'Praestigia sibirica',
        'Primerigonina australis',
        'Primerigonina sp. 2 FML',
        'Prinerigone vagans',
        'Prosoponoides sinensis',
        'Pseudafroneta incerta',
        'Pseudocyba miracula',
        'Ryojius sp.',
        'Saaristoa abnormis',
        'Saaristoa ebinoensis',
        'Saaristoa firma',
        'Saaristoa sammamish',
        'Saloca diceros',
        'Satilatlas britteni',
        'Satilatlas gertschi',
        'Satilatlas marxi',
        'Satilatlas monticola',
        'Savignia frontata',
        'Savignia sp.',
        'Scandichrestus tenuis',
        'Sciastes dubius',
        'Sciastes extremus',
        'Sciastes hastatus',
        'Sciastes mentasta',
        'Sciastes truncatus',
        'Scirites finitimus',
        'Scirites pectinatus',
        'Scironis sima',
        'Scironis tarsalis',
        'Scolopembolus littoralis',
        'Scotargus pilosus',
        'Scotinotylus alpigena',
        'Scotinotylus alpinus',
        'Scotinotylus bicavatus',
        'Scotinotylus clavatus',
        'Scotinotylus columbia',
        'Scotinotylus eutypus',
        'Scotinotylus evansi',
        'Scotinotylus exsectoides',
        'Scotinotylus kenus cf.',
        'Scotinotylus levii',
        'Scotinotylus majesticus',
        'Scotinotylus pallidus',
        'Scotinotylus patellatus',
        'Scotinotylus protervus',
        'Scotinotylus pr. sanctus',
        'Scotinotylus sacer',
        'Scotinotylus sanctus',
        'Scotinotylus sp.',
        'Scotinotylus sp. 1GAB',
        'Scotinotylus sp. 2GAB',
        'Scotinotylus sp. 3GAB',
        'Scotinotylus sp. 6GAB',
        'Scotinotylus tianschanicus',
        'Scotinotylus vernalis',
        'Scylaceus pallidus',
        'Scyletria inflata',
        'Semljicola alticola',
        'Semljicola beringianus',
        'Semljicola faustus',
        'Semljicola lapponicus',
        'Semljicola latus',
        'Semljicola obtusus',
        'Semljicola sp. 1GAB',
        'Semljicola sp. 3GAB',
        'Silometopoides pampia',
        'Silometopoides pingrensis',
        'Silometopus ambiguus',
        'Silometopus elegans',
        'Silometopus incurvatus',
        'Silometopus reussi',
        'Sintula corniger',
        'Sintula retroversus',
        'Sintula spiniger',
        'Sisicottus crossoclavis',
        'Sisicottus montanus',
        'Sisicottus nesides',
        'Sisicottus orites',
        'Sisicottus panopeus',
        'Sisicus apertus',
        'Sisicus penifusifer',
        'Sisis rotundus',
        'Smerasia obscurus',
        'Solenysa longqiensis',
        'Solenysa melloteei',
        'Solenysa partibilis',
        'Solenysa protrudens',
        'Solenysa reflexilis',
        'Solenysa retractilis',
        'Solenysa tianmushana',
        'Solenysa wulingensis',
        'Soucron arenarium',
        'Souessa spinifera',
        'Souessoula parva',
        'Soulgas corticarius',
        'Soulgas sp. 1GAB',
        'Sphecozone bicolor',
        'Sphecozone modica',
        'Sphecozone sp.',
        'Spirembolus abnormis',
        'Spirembolus chilkatensis',
        'Spirembolus demonologicus',
        'Spirembolus hibernus cf.',
        'Spirembolus monticolens',
        'Spirembolus mundus',
        'Spirembolus prominens',
        'Spirembolus sp.',
        'Spirembolus sp. 1 GAB',
        'Stemonyphantes abantensis',
        'Stemonyphantes blauveltae',
        'Stemonyphantes lineatus',
        'Stemonyphantes sibiricus',
        'Styloctetor cf. romana',
        'Styloctetor lehtineni',
        'Styloctetor purpurescens',
        'Styloctetor romanus',
        'Styloctetor stativus',
        'Syedra myrmicarum',
        'Symmigma minimum',
        'Tachygyna coosi',
        'Tachygyna haydeni',
        'Tachygyna pallida',
        'Tachygyna proba',
        'Tachygyna ursina',
        'Tachygyna vancouverana',
        'Tallusia experta',
        'Tapinocyba affinis',
        'Tapinocyba affinis cf.',
        'Tapinocyba bicarinata',
        'Tapinocyba biscissa',
        'Tapinocyba cameroni',
        'Tapinocyba cf. simplex',
        'Tapinocyba dietrichi',
        'Tapinocyba hortensis',
        'Tapinocyba insecta',
        'Tapinocyba kolymensis',
        'Tapinocyba lindrothi',
        'Tapinocyba minuta',
        'Tapinocyba minuta cf.',
        'Tapinocyba pallens',
        'Tapinocyba parva',
        'Tapinocyba praecox',
        'Tapinocyba prima',
        'Tapinocyba simplex',
        'Tapinocyboides pygmaeus',
        'Tapinopa bilineata',
        'Tapinopa guttata',
        'Tapinopa longidens',
        'Taranucnus setosus',
        'Tarsiphantes latithorax',
        'Tennesseellum formica',
        'Tenuiphantes alacris',
        'Tenuiphantes cristatus',
        'Tenuiphantes flavipes',
        'Tenuiphantes floriana',
        'Tenuiphantes herbicola',
        'Tenuiphantes jacksoni',
        'Tenuiphantes jacksonoides',
        'Tenuiphantes mengei',
        'Tenuiphantes nigriventris',
        'Tenuiphantes sabulosus',
        'Tenuiphantes sp.',
        'Tenuiphantes tenebricola',
        'Tenuiphantes tenuis',
        'Tenuiphantes zebra',
        'Tenuiphantes zelatus',
        'Tenuiphantes zibus',
        'Tenuiphantes zimmermanni',
        'Ternatus malleatus',
        'Ternatus siculus',
        'Thaleria leechi',
        'Thaleria sp. 1GAB',
        'Theoa bidentata',
        'Theoa vesica',
        'Theonina cornix',
        'Thyreosthenius biovatus',
        'Thyreosthenius parasiticus',
        'Tibioploides arcuatus',
        'Tibioploides pacificus',
        'Tibioplus diversus',
        'Tiso aestivus',
        'Tiso vagans',
        'Tmeticus affinis',
        'Tmeticus nigriceps',
        'Tmeticus ornatus',
        'Tmeticus tolli',
        'Toschia minuta',
        'Trematocephalus cristatus',
        'Trichoncoides piscator',
        'Trichoncus hackmani',
        'Trichopterna cito',
        'Trichopternoides thorelli',
        'Troglohyphantes drenskii',
        'Troglohyphantes karolianus',
        'Troglohyphantes pisidicus',
        'Troglohyphantes pretneri',
        'Troxochrus scabriculus',
        'Tubercithorax subarcticus',
        'Tunagyna debilis',
        'Typhochrestus digitatus',
        'Typhochrestus pygmaeus',
        'Ummeliata insecticeps',
        'Vagiphantes vaginatus',
        'Vermontia thoracica',
        'Vittatus bian',
        'Vittatus fencha',
        'Vittatus latus',
        'Vittatus pan',
        'Wabasso cacuminatus',
        'Wabasso quaestio',
        'Wabasso replicatus',
        'Walckenaeria acuminata',
        'Walckenaeria aenea',
        'Walckenaeria alticeps',
        'Walckenaeria antica',
        'Walckenaeria arctica',
        'Walckenaeria atrotibialis',
        'Walckenaeria auranticeps',
        'Walckenaeria brevicornis',
        'Walckenaeria capito',
        'Walckenaeria castanea',
        'Walckenaeria clavicornis',
        'Walckenaeria columbia',
        'Walckenaeria communis',
        'Walckenaeria corniculans',
        'Walckenaeria cornuella',
        'Walckenaeria crocea',
        'Walckenaeria cucullata',
        'Walckenaeria cuspidata',
        'Walckenaeria cuspidata brevicula',
        'Walckenaeria digitata',
        'Walckenaeria directa',
        'Walckenaeria dysderoides',
        'Walckenaeria exigua',
        'Walckenaeria fallax',
        'Walckenaeria fraudatrix',
        'Walckenaeria furcillata',
        'Walckenaeria intoleranda',
        'Walckenaeria karpinskii',
        'Walckenaeria kochi',
        'Walckenaeria korobeinikovi',
        'Walckenaeria lepida',
        'Walckenaeria mitrata',
        'Walckenaeria monoceros',
        'Walckenaeria nodosa',
        'Walckenaeria nr. spiralis',
        'Walckenaeria nudipalpis',
        'Walckenaerianus aimakensis',
        'Walckenaeria obtusa',
        'Walckenaeria occidentalis',
        'Walckenaeria pallida',
        'Walckenaeria palustris',
        'Walckenaeria pellax',
        'Walckenaeria pinocchio',
        'Walckenaeria prominens',
        'Walckenaeria redneri',
        'Walckenaeria sp.',
        'Walckenaeria sp. 10 FML',
        'Walckenaeria sp. 11 FML',
        'Walckenaeria sp. 13 FML',
        'Walckenaeria sp. 1 FML',
        'Walckenaeria sp. 2GAB',
        'Walckenaeria sp. 4GAB',
        'Walckenaeria spiralis',
        'Walckenaeria subdirecta',
        'Walckenaeria subspiralis',
        'Walckenaeria tibialis',
        'Walckenaeria tricornis',
        'Walckenaeria tumida',
        'Walckenaeria tystchenkoi',
        'Walckenaeria unicornis',
        'Walckenaeria vigilax',
        'Wubana atypica',
        'Wubana drassoides',
        'Wubana pacifica',
        'Wubana sp.',
        'Wubana sp. 1JS',
        'Wubana suprema',
        'Wubanoides fissus',
        'Wubanoides sp.',
        'Zornella armata',
        'Zornella cryptodon',
        'Zornella cultrigera',
        'Zygottus corvallis',
        'Zygottus sp.',
    ]
];
